// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CreateProductRequest defines model for CreateProductRequest.
type CreateProductRequest struct {
	Description   *string `json:"description,omitempty"`
	Name          string  `json:"name"`
	Price         float32 `json:"price"`
	Sku           string  `json:"sku"`
	StockQuantity *int    `json:"stockQuantity,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Details *string `json:"details"`
	Message string  `json:"message"`
}

// MonthlySalesStats defines model for MonthlySalesStats.
type MonthlySalesStats struct {
	Months []MonthlyStat `json:"months"`
}

// MonthlyStat defines model for MonthlyStat.
type MonthlyStat struct {
	// AverageOrderValue Average order value
	AverageOrderValue float32 `json:"averageOrderValue"`

	// Month Month in format YYYY-MM
	Month string `json:"month"`

	// TotalOrders Total number of orders
	TotalOrders int `json:"totalOrders"`

	// TotalRevenue Total revenue for the month
	TotalRevenue float32 `json:"totalRevenue"`
}

// Product defines model for Product.
type Product struct {
	CreatedAt     time.Time          `json:"createdAt"`
	Description   *string            `json:"description"`
	Id            openapi_types.UUID `json:"id"`
	Name          string             `json:"name"`
	Price         float32            `json:"price"`
	Sku           string             `json:"sku"`
	StockQuantity int                `json:"stockQuantity"`
	UpdatedAt     *time.Time         `json:"updatedAt"`
}

// ProductList defines model for ProductList.
type ProductList struct {
	Products []Product `json:"products"`
	Total    int       `json:"total"`
}

// UpdateProductRequest defines model for UpdateProductRequest.
type UpdateProductRequest struct {
	Description   *string  `json:"description,omitempty"`
	Name          *string  `json:"name,omitempty"`
	Price         *float32 `json:"price,omitempty"`
	StockQuantity *int     `json:"stockQuantity,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// InternalError defines model for InternalError.
type InternalError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ListProductsParams defines parameters for ListProducts.
type ListProductsParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateProductJSONRequestBody defines body for CreateProduct for application/json ContentType.
type CreateProductJSONRequestBody = CreateProductRequest

// UpdateProductJSONRequestBody defines body for UpdateProduct for application/json ContentType.
type UpdateProductJSONRequestBody = UpdateProductRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all products
	// (GET /products)
	ListProducts(ctx echo.Context, params ListProductsParams) error
	// Create a new product
	// (POST /products)
	CreateProduct(ctx echo.Context) error
	// Delete a product
	// (DELETE /products/{productId})
	DeleteProduct(ctx echo.Context, productId openapi_types.UUID) error
	// Get a product by ID
	// (GET /products/{productId})
	GetProduct(ctx echo.Context, productId openapi_types.UUID) error
	// Update a product
	// (PUT /products/{productId})
	UpdateProduct(ctx echo.Context, productId openapi_types.UUID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListProducts converts echo context to params.
func (w *ServerInterfaceWrapper) ListProducts(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListProductsParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListProducts(ctx, params)
	return err
}

// CreateProduct converts echo context to params.
func (w *ServerInterfaceWrapper) CreateProduct(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateProduct(ctx)
	return err
}

// DeleteProduct converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteProduct(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "productId" -------------
	var productId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "productId", ctx.Param("productId"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter productId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteProduct(ctx, productId)
	return err
}

// GetProduct converts echo context to params.
func (w *ServerInterfaceWrapper) GetProduct(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "productId" -------------
	var productId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "productId", ctx.Param("productId"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter productId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetProduct(ctx, productId)
	return err
}

// UpdateProduct converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateProduct(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "productId" -------------
	var productId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "productId", ctx.Param("productId"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter productId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateProduct(ctx, productId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/products", wrapper.ListProducts)
	router.POST(baseURL+"/products", wrapper.CreateProduct)
	router.DELETE(baseURL+"/products/:productId", wrapper.DeleteProduct)
	router.GET(baseURL+"/products/:productId", wrapper.GetProduct)
	router.PUT(baseURL+"/products/:productId", wrapper.UpdateProduct)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xYbW/bNhD+K8StH+X4pRlQ6Fu6boWBZsvabUDQdsBFOttsJVIlT14NQ/99ICnZlsXG",
	"yZBk/RTZPN3Lc889PGcLmS4rrUixhXQLhmyllSX/4SXmb+lLTZbdp0wrJuUfsaoKmSFLrcafrFbuO5ut",
	"qET39MzQAlL4Ybx3PQ6ndvyzMdpA0zQJ5GQzIyvnBFIXS5g2WJPAXDEZhUWwf/ToXThhyazJCAqGCfyq",
	"+Rddq/zxU3hLVtcmI6E0i4WP6Yza95zbnwwh05XReZ3xQWMqoysyLEPTel63wJuKIAXLRqqlq0hhSe6g",
	"xK9vSC15BelsMkmGhpWRmbdcaFMiQwqLQiNDAqVUsqxLSPevqbq8IY+Y/VwfuZ9G3VvW2effa1QseRMS",
	"X2BdsPcaiSAV09KFaBJwRJGGckjf+3htVV3OH3cv6ZtPlHlC7Yh0jBajLPyjqosCbwqClE1NkYxLshaX",
	"FEH1KKXOMJbHpVa8KjbvsCD7jjFMXT+n0pn4J8lU2lOM6jwy+gBtRDQGN8PMguvbEnNuBinhmgwu6TeT",
	"k/kLi5oGTIOLYCK0sxFrb5Tckzs+vaFrn5qQSgRv4vr6+np0eQkJ0FcsK9cymE1m56Pp1HEA2Q0zpPD3",
	"hw/59rwZuT+z5hlEesqasfBlDYcH/nCHIqQn9CKUZuF2erY+39KaVAyn4NSEY1eR4BWJUPn98Ir1Fo7C",
	"9ytMIo2McaHVmCEPMi9B+QX3dCFHphFLP4EDhI/06OSUybznu65lHnP73crY7dyoq/wEgCcAOmq6Byci",
	"gceJJQetu6Xjb2TsSqnC4d0lqePPQI5aOh5I6LdkfRezeyWW9Z8eze/+RrwPRZpBme4rqRY6IrlXcy8g",
	"JSpcSrUUHWhJK1WJQJUL6+4agQqLDcvMIyrZi+alVHJ0YT6TGIlLVPUCM65dte4TLqkkxeLiag4JrMnY",
	"EHV6NjmbuLp0RQorCSk8P5ucPQ/SGy6u8SFlluSb4lriN6Z5Dik4pl3te1yhwZLYy/D7LUgX6EtNZtMR",
	"O4VCltJhvd+zdhvDzK0M+DWA6ud0B/E0BnE8gF4sLH0jwqmd5GPSX51nk8mDrYyHsxlZHN337nbaQd4k",
	"8GMIH/O6S3Pc37H9slmXJZpN5xSLoue10jbSyd5aCmGKyfJLnW8eDILo6tv0NcPJZTNow/Sh2xBrQXsk",
	"Wo11WJ3fpQMHP7AeomkBJYFC0T9d47zJbhzH2/ZpnjeB3wUxDXv6yn9/2NMeqOdDLeogCB5bCM5P17P7",
	"gfUQAIS0Be6LT+Lq85r4m8VNnpIx3e+P/wWu18R7rMTNRsxf+TGPaLFT9r1S7kgExwN4KJ4ndjinmVUd",
	"aU7vVn8kQYluDncSlCelR7su/kdBeXpGBVgPB9Cf+3+qBDYd3V06w0LktKZCV37bCLaQQG0KSGHFXKXj",
	"ceHsVtpy+mLyYgLNx+bfAAAA///zjZ48uRIAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
